import 'dart:io';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:path/path.dart' as p;
import 'package:intl/intl.dart';

final githubAutomationProvider = Provider((ref) => GitHubAutomationService());

class GitHubAutomationService {
  final String _repoPath = Directory.current.path;
  final String _clientAppPath = p.join(Directory.current.path, 'roster_iq');
  final String _ghPath = p.join(Directory.current.path, 'roster_iq', 'gh');

  /// Executes the full production release pipeline.
  Stream<String> publishRelease(String version, String buildNotes) async* {
    yield '--- STARTING PRODUCTION RELEASE PIPELINE [v$version] ---';

    // 1. Build Android APK
    yield 'BUILDING ANDROID APK...';
    final apkResult = await Process.run(
      'flutter', 
      ['build', 'apk', '--release', '--no-tree-shake-icons'],
      workingDirectory: _clientAppPath,
    );
    if (apkResult.exitCode != 0) {
      yield 'ERROR: Android Build Failed: ${apkResult.stderr}';
      return;
    }
    yield '✓ Android APK Built.';

    // 2. Build Web
    yield 'BUILDING WEB DISTRIBUTION...';
    final webResult = await Process.run(
      p.join(_clientAppPath, 'build_web.sh'),
      [],
      workingDirectory: _clientAppPath,
    );
     if (webResult.exitCode != 0) {
      yield 'ERROR: Web Build Failed: ${webResult.stderr}';
      return;
    }
    yield '✓ Web Distribution Built.';

    // 3. Git Push
    yield 'PUSHING SOURCE CODE TO GITHUB...';
    // We rely on the .gitignore to exclude command_center and asset_sources
    await Process.run('git', ['add', '.'], workingDirectory: _repoPath);
    await Process.run('git', ['commit', '-m', 'Release v$version'], workingDirectory: _repoPath);
    await Process.run('git', ['push', 'origin', 'main'], workingDirectory: _repoPath);
    yield '✓ Source Code Pushed.';

    // 4. Discover Documentation
    yield 'DISCOVERING RELEASE DOCUMENTATION...';
    final notes = await _generateReleaseNotes(version);
    yield '✓ Documentation aggregated.';

    // 5. Create GitHub Release using local 'gh' binary
    yield 'CREATING GITHUB RELEASE...';
    final releaseResult = await Process.run(
      _ghPath,
      [
        'release', 'create', 'v$version',
        '--title', 'Pokemon Generations v$version',
        '--notes', notes,
        p.join(_clientAppPath, 'build', 'app', 'outputs', 'flutter-apk', 'app-release.apk'),
      ],
      workingDirectory: _repoPath,
    );

    if (releaseResult.exitCode != 0) {
      yield 'ERROR: GitHub Release Failed: ${releaseResult.stderr}';
      return;
    }

    yield '--- RELEASE v$version PUBLISHED SUCCESSFULLY ---';
  }

  Future<String> _generateReleaseNotes(String version) async {
    final date = DateFormat('yyyy-MM-dd').format(DateTime.now());
    final changelogPath = p.join(_repoPath, 'public', 'changelog_v$version.md');
    // Note: devchangelog_v$version.md in /devops/ is EXCLUDED from public release notes.
    final newsPath = p.join(_repoPath, 'public', 'news_$date.md');

    String body = '## Release v$version ($date)\n\n';

    if (await File(changelogPath).exists()) {
      body += '### 📜 Changelog\n${await File(changelogPath).readAsString()}\n\n';
    }
    
    if (await File(newsPath).exists()) {
      body += '### 📰 Latest News\n${await File(newsPath).readAsString()}\n\n';
    }

    body += '---\n*Automatically generated by Pokemon Generations Production Automation.*';
    return body;
  }
}
